export const projects = [
  {
    title: 'Online Food Delivery',
    description: "This app make it convenient and engaging for customers to buy food online",
    image: '/images/port1.png',
    tags: ['React', 'Firebase', 'Styled Component'],
    source: 'https://github.com/sujit995/food-order-app',
    visit: 'https://sujit995-onlinefood-delivery.netlify.app',
    id: 0,
  },
  {
    title: 'Photo Gallery',
    description: "Responsive gallery for posting and viewing images in a secure and simple manner",
    image: '/images/port2.png',
    tags: ['React', 'JavaScript', 'Firebase', 'Styled Component'],
    source: 'https://github.com/sujit995/photo-gallery-app',
    visit: 'https://sujit995-photo-gallery.netlify.app',
    id: 1,
  },
  {
    title: 'Minichat App',
    description: "This is a simple chat app where users can group chat with each other. An user need to signin before chatting in a group.",
    image: '/images/port3.png',
    tags: ['React', 'Firebase'],
    source: 'https://github.com/sujit995/mini-chat-app',
    visit: 'https://mini-chat-app.netlify.app/',
    id: 2,
  },
  {
    title: 'Movie Search App',
    description: "An User can search and see the information about their favorite movie",
    image: '/images/port4.png',
    tags: ['React', 'IMDB Api'],
    source: 'https://github.com/sujit995/movie-details-app',
    visit: 'https://sujit995-movie-app.netlify.app',
    id: 3,
  },
];
